services:
  frpc:
    container_name: frpc
    restart: always
    network_mode: host
    volumes:
      # {{docker_root}} 部署时自动替换为设置中配置的容器安装目录
      - "{{docker_root}}/frpc/frpc.toml:/etc/frp/frpc.toml"
    image: snowdreamtech/frpc:latest
networks: {}
