services:
  alist:
    container_name: alist
    restart: always
    network_mode: bridge
    ports:
      - 5244:5244
    volumes:
      # {{docker_root}} 部署时自动替换为商店设置中配置的容器安装目录
      - "{{docker_root}}/alist:/opt/alist/data"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    image: xhofe/alist:v3.45.0
networks: {}
