services:
  onestrm:
    image: lifj25/onestrm:latest
    container_name: onestrm
    restart: always
    network_mode: bridge
    ports:
      - 18003:18003
      # emby服务器直链端口，可映射多个，内部设置对应emby
      - 8099:8099
    volumes:
      - "{{docker_root}}/onestrm/config:/app/config"
      # {{strm_dir}} 请改为实际 STRM 文件目录，如 /vol4/1000/media
      - "{{strm_dir}}/media:/media"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
