services:
  clouddrive2:
    container_name: clouddrive2
    restart: always
    network_mode: bridge
    environment:
      - CLOUDDRIVE_HOME=/Config
    volumes:
      - "{{docker_root}}/clouddrive2:/Config"
      # {{mount_dir}} 请改为实际挂载目录（最终路径为 {{mount_dir}}/cd2），如 /vol4/1000
      - "{{mount_dir}}/cd2:/CloudNAS:shared"
    ports:
      - 19798:19798
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    image: cloudnas/clouddrive2
networks: {}
